### ISSUE TITLE
Software for differential expression analysis from rpvg's readcount

### ISSUE THREAD

**Issue by lsoldini** [jonassibbesen/rpvg#37]
**Overall question**

Which software would you advise to perform differential expression analysis on the ReadCount produced by rpvg ?

**Context**

I've used the `mpmap-rpvg` pipeline to 1) map RNA-seq reads, 2) quantify their expression. I now have set of files with ReadCount for each genomic feature and I would want to perform differential expression analysiss.

**Thoughts**
From the "haplotype specific ..." paper:
"While HST expression estimates can always be marginalized to produce allele or transcript expression estimates, more general statistical frameworks will need to be developed to avoid information loss between these steps in transcriptomic pipelines". 

I understand that, in the ideal scenario, it would be required to have something coming after mpmap and rpvg to specfically make use of all the information from those pantranscriptomic methods, and to build proper statistical model to perform differential expression analysis. 

But, in the meantime, I was wondering if any of the existing software for differential expression analysis could be suited ? For instance, what do you think about Sleuth (Patcher lab, designed to work with kallisto's).

**Comment by lsoldini** [comment]
Also, from the "haplotype specific ..." paper (bioRxiv 2022), it seems to me that sleuth would be the most appropriate available because there are several instances were the formulas used are similar to the one used by kallisto/salmon (e.g., effective transcript length, EM algorithm convergence criterion, etc.). 

However, the typical kallisto output contains a "estimated counts" column, while rpvg rather outputs a "read counts" column. Is there some way to output estimate counts from rpvg ? (I did not find it from the rpvg's --help). Or, maybe, there is some way to compute it from the rpvg output ?

**Comment by jonassibbesen** [comment]
Hi, sorry for the late reply. Have been on vacation. 

If you are primarily interested in transcript expression I would imagine that most differential transcript expression methods that work with expression estimates from Kallisto, Salmon etc. would also work with rpvg. Like Sleuth, edgeR etc. However, it is not something I have experience with. You would likely need to change the output format so that it matches what is expected by the methods, but it seems like you are already aware of that. 

Differential expression analysis is not something we have explored much yet, but it is something we are really interested in. You are right that in the ideal case we would want to use a method that models differences in both the haplotype and transcript expression, but such a method does not exist yet to our knowledge.

**Comment by lsoldini** [comment]
Hi, no problem, sorry for my late reply as well.

So, at the end, I used edgeR, which indeed required some output re-formating, but it was quite straightforward (once the software was decided). It gave results similar to what we had when we used kallisto (i.e., not based on rpvg), although we did not extensively assessed and compared their results.

**Comment by CarlosAmadeo7** [comment]
Hello Isoldini
I am Carlos, and I have started to wonder how I can do a differential expression analysis of the haplotype-transcript expression I got as the output of rpvg. I was reading the issues of rpvg to find information and I read your comment, if you don't mind I would like to ask you a couple of questions:
Did you use the single haplotype or the dyplotype output to marginalize the haplotypes?
How did you do the marginalization, if you don't mind? ( I am new and learning quick)
You mentioned that you changed the output format, How come? Can you give me more information, please

I appreciate your time
